apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas
  namespace: code-server
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.2.15
    path: "/mnt/sda3/microk8s"
